"""Incident report + detection-rule generation.

Default: deterministic, grounded template (works offline, no API key). If a local
OpenAI-compatible LLM is reachable (Ollama / LM Studio, set LLM_BASE_URL), it writes the
executive summary from the same facts.
"""
from __future__ import annotations

import json
import os
import uuid
from collections.abc import Iterator

import httpx

LLM_BASE_URL = os.getenv("LOCAL_LLM_BASE_URL", "http://localhost:11434/v1")
LLM_MODEL = os.getenv("LOCAL_LLM_MODEL", "qwen2.5:7b")


def llm_available() -> bool:
    try:
        return httpx.get(f"{LLM_BASE_URL}/models", timeout=0.5).status_code == 200
    except httpx.HTTPError:
        return False


def sigma_rule(state: dict) -> str:
    iocs = sorted({i for d in state["decodes"] for i in d["iocs"]})
    hosts = [state["hunt"]["source_host"], *state["hunt"]["compromised"]]
    techniques = [t["id"].lower() for t in state["techniques"][:4]]
    tags = "\n".join(f"    - attack.{t}" for t in techniques)
    domains = sorted({i.split("/")[2] for i in iocs if i.startswith("http")})
    return f"""title: Encoded PowerShell Download Cradle via Office or WMI Parent
id: {uuid.uuid5(uuid.NAMESPACE_URL, 'soc-copilot:' + ','.join(hosts))}
status: experimental
description: |
    Generated by SOC Copilot from incident {state['incident_name']}.
    Matches encoded PowerShell launched by Office or WmiPrvSE that decodes to a
    remote download-and-execute cradle. Seen on {', '.join(hosts)}.
author: SOC Copilot (Qdrant + Cognee)
tags:
{tags}
logsource:
    category: process_creation
    product: windows
detection:
    selection_parent:
        ParentImage|endswith:
            - '\\WINWORD.EXE'
            - '\\EXCEL.EXE'
            - '\\WmiPrvSE.exe'
    selection_img:
        Image|endswith:
            - '\\powershell.exe'
            - '\\pwsh.exe'
    selection_enc:
        CommandLine|contains:
            - ' -e '
            - ' -enc '
            - ' -EncodedCommand '
    selection_cradle_b64:
        CommandLine|wide|base64offset|contains:  # PowerShell -enc is UTF-16LE
            - 'DownloadString'
            - 'iwr -UseBasicParsing'
            - 'Invoke-Expression'
    filter_intune:
        ParentImage|endswith: '\\AgentExecutor.exe'
    condition: selection_parent and selection_img and selection_enc and selection_cradle_b64 and not filter_intune
falsepositives:
    - Legitimate software deployment tools using encoded download cradles (rare)
level: high
# IOC watchlist: {', '.join(domains + [i for i in iocs if not i.startswith('http')])}
"""


def _facts(state: dict) -> dict:
    h = state["hunt"]
    g = state["graph"]
    return {
        "patient_zero": h["source_host"],
        "compromised": h["compromised"],
        "lateral": h["lateral"],
        "techniques": [f"{t['id']} {t['name']}" for t in state["techniques"][:6]],
        "groups": [f"{x['name']} ({x['id']}, {len(x['overlap'])} TTP overlap)" for x in g["groups"]],
        "predicted": [f"{p['id']} {p['name']}" for p in g["predicted"]],
        "mitigations": [f"{m['id']} {m['name']}" for m in g["mitigations"]],
        "iocs": sorted({i for d in state["decodes"] for i in d["iocs"]}),
        "user": state["alert"]["user"],
    }


def _template_summary(f: dict) -> str:
    actor = f["groups"][0].split(" (")[0] if f["groups"] else "no known actor"
    nxt = ", ".join(p.split(" ", 1)[1] for p in f["predicted"][:2]) or "no clear next step"
    return (
        f"An alert on **{f['patient_zero']}** (user `{f['user']}`) exposed an encoded PowerShell download "
        f"cradle to {', '.join('`' + i + '`' for i in f['iocs']) or 'an external host'}. Behavioural hunting in "
        f"Qdrant found **{len(f['compromised'])} additional hosts** ({', '.join(f['compromised'])}) running "
        f"*different* payloads with the same behaviour and no alerts of their own. The observed TTPs overlap "
        f"most with **{actor}** in the Cognee ATT&CK graph; peer groups with the same tradecraft typically "
        f"continue with {nxt}."
    )


def _llm_summary(f: dict) -> Iterator[str]:
    prompt = ("You are a SOC analyst. Write a 3-sentence executive summary of this incident using ONLY "
              "these facts. No speculation beyond them.\n" + json.dumps(f, indent=1))
    with httpx.stream("POST", f"{LLM_BASE_URL}/chat/completions", timeout=60, json={
        "model": LLM_MODEL, "stream": True, "temperature": 0.2,
        "messages": [{"role": "user", "content": prompt}]}) as r:
        for line in r.iter_lines():
            if line.startswith("data: ") and line != "data: [DONE]":
                delta = json.loads(line[6:])["choices"][0]["delta"].get("content")
                if delta:
                    yield delta


def stream_report(state: dict) -> Iterator[str]:
    f = _facts(state)
    yield f"## Incident {state['incident_name']}\n\n"
    yield "### Executive summary\n"
    if llm_available():
        try:
            yield from _llm_summary(f)
        except httpx.HTTPError:
            yield _template_summary(f)
    else:
        yield _template_summary(f)
    yield "\n\n### Scope\n"
    yield f"- **Patient zero:** {f['patient_zero']}\n"
    for lat in f["lateral"]:
        yield f"- **{lat['target']}** ← {lat['source']} via `{lat['via']}` at {lat['time']}\n"
    yield "\n### Observed ATT&CK techniques\n"
    for t in f["techniques"]:
        yield f"- {t}\n"
    yield "\n### Likely actor (Cognee graph)\n"
    for g in f["groups"]:
        yield f"- {g}\n"
    yield "\n### Predicted next moves\n"
    for p in f["predicted"]:
        yield f"- {p}\n"
    yield "\n### Recommended actions\n"
    yield f"1. Isolate {', '.join([f['patient_zero'], *f['compromised']])} from the network\n"
    yield f"2. Block IOCs at the proxy / firewall: {', '.join('`' + i + '`' for i in f['iocs'])}\n"
    yield f"3. Reset credentials for `{f['user']}` and all accounts cached on the affected hosts (LSASS was dumped)\n"
    yield "4. Hunt for the predicted next moves above across the fleet; watch DC-01 / DC-02 closely\n"
    yield f"5. Apply mitigations: {', '.join(f['mitigations'])}\n"
    yield "\n### Generated detection rule (Sigma)\n```yaml\n"
    yield sigma_rule(state)
    yield "```\n"
